export const setUserStatus = "setUserStatus"
export const addToAppBarLinks = "addToAppBarLinks"
export const deleteFromAppBarLinks = "deleteFromAppBarLinks"
export const setAppBarLinks = "setAppBarLinks"
export const setuserIsManager = "setuserIsManager"
export const setUsername = "setUsername"
